on:
  - push
  - pull_request

name: Main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            rust-target: x86_64-pc-windows-msvc
            artifact-name: win64
          - os: windows-latest
            rust-target: i686-pc-windows-msvc
            artifact-name: win32
          - os: ubuntu-16.04
            rust-target: x86_64-unknown-linux-gnu
            artifact-name: linux
          - os: macos-latest
            rust-target: x86_64-apple-darwin
            artifact-name: mac
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: mtkennerly/dunamai-action@v1
        with:
          env-var: LUDUSAVI_VERSION
          args: --style semver
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.rust-target }}
          override: true
      - run: sudo apt-get update && sudo apt-get install -y gcc libxcb-composite0-dev
        if: ${{ matrix.os == 'ubuntu-16.04' }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - run:
          mkdir dist
          cp target/release/ludusavi dist
        if: ${{ matrix.os != 'windows-latest' }}
      - run:
          mkdir dist
          copy target/release/ludusavi.exe dist
          copy assets/ludusavi.ico dist
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: actions/upload-artifact@v2
        with:
          name: ludusavi-v${{ env.LUDUSAVI_VERSION }}-${{ matrix.artifact-name }}
          path: dist/*

  test:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: sudo apt-get update && sudo apt-get install -y gcc libxcb-composite0-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - run: reg import tests/ludusavi.reg
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: actions-rs/cargo@v1
        with:
          command: test

  lint:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
